name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - numpy=1.26.4
  - pandas=2.2.3
  - scikit-learn=1.3.1
  - matplotlib=3.10.1
  - seaborn=0.13.2
  - jupyter=1.0.0
  - jupyterlab=4.3.5
  - nltk=3.9.1
  - gensim=4.3.3
  - wordcloud=1.9.4
  - tqdm=4.67.1
  - pip=25.0.1
  - pip:
    - huggingface-hub==0.30.1
    - datasets==3.5.0
    - transformers==4.30.0
    - pyldavis==3.4.1