name: base
channels:
  - gurobi
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.11.9
  - numpy=1.26.4
  - pandas=2.2.3
  - scikit-learn=1.3.1
  - matplotlib=3.10.1
  - seaborn=0.13.2
  - jupyter=1.0.0
  - jupyterlab=4.3.5
  - ipykernel=6.29.5
  - ipython=9.0.0
  - pip=25.0.1
  - pip:
    - sympy==1.13.1
    - huggingface-hub==0.30.1
  - gurobi=12.0.1
  - xgboost=2.1.4
  - shap=0.47.1
  - transformers=4.30.0
  - datasets=3.5.0
  - pytorch=2.4.1
  - torchvision
  - torchaudio
  - tensorflow
  - keras
  - nltk=3.9.1
  - spacy
  - gensim=4.3.3
  - wordcloud=1.9.4
  - statsmodels=0.14.4
  - scipy=1.15.2
  - networkx=3.4.2
  - plotly
  - bokeh=3.6.3
  - pyarrow=16.1.0
  - opencv-python
  - pillow=11.0.0
  - tqdm=4.67.1
  - requests=2.32.3
  - beautifulsoup4=4.13.3
  - lxml
  - html5lib
  - python-dotenv=1.0.1
  - pyyaml=6.0.2
  - joblib=1.4.2
  - numba=0.61.0
  - llvmlite=0.44.0
  - cython=3.0.12
  - line_profiler=4.2.0
  - memory_profiler
  - psutil=7.0.0
  - pytest
  - black
  - flake8
  - mypy
  - isort
  - pre-commit